In [1]:
#1. kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#2. Veri Onisleme

#2.1. Veri Yukleme
veriler = pd.read_csv('C:/Users/muham/Veriler/odev_tenis.csv')
#pd.read_csv("veriler.csv")

In [4]:
veriler.head()

outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

In [5]:
#veri on isleme

#encoder:  Kategorik -> Numeric
from sklearn.preprocessing import LabelEncoder
veriler2 = veriler.apply(LabelEncoder().fit_transform)
#Bu kod parçacığı bütün veriye label encoder uygulayarak tek bir sütunda numaralandırır. 2 değişkenli sütunlar için idealdir.

In [7]:
veriler2
#Buradaki outlook sütununda 3 değişken olduğu içine 'OHE' uygulamamız gerekiyor.

outlook  temperature  humidity  windy  play
0         2           11         4      0     0
1         2            8         6      1     0
2         0           10         5      0     1
3         1            4         9      0     1
4         1            2         3      0     1
5         1            1         1      1     0
6         0            0         0      1     1
7         2            6         8      0     0
8         2            3         1      0     1
9         1            7         3      0     1
10        2            7         1      1     1
11        0            6         6      1     1
12        0            9         2      0     1
13        1            5         7      1     0

In [13]:
c = veriler2.iloc[:,:1]
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
c=ohe.fit_transform(c).toarray()
print(c)
#Bu kod parçacığunda ise yukarıda dediğimiz gibi outlook sütununa ohe uygulamış bulunmaktayız.

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [14]:
havadurumu = pd.DataFrame(data = c, index = range(14), columns=['o','r','s'])
sonveriler = pd.concat([havadurumu,veriler.iloc[:,1:3]],axis = 1)
sonveriler = pd.concat([veriler2.iloc[:,-2:],sonveriler], axis = 1)

In [26]:
#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(sonveriler.iloc[:,:-1],sonveriler.iloc[:,-1:],test_size=0.33, random_state=0)

In [30]:
#Verilerin tahminlenmesi
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [31]:
y_pred=regressor.predict(x_test)

In [32]:
y_pred

array([[84.45365573],
       [63.93839954],
       [85.76050662],
       [64.21013241],
       [75.06793322]])

In [34]:
y_test

humidity
8         70
6         65
4         80
11        90
2         86

In [39]:
import statsmodels.formula.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1 )
X_l = sonveriler.iloc[:,[0,1,2,3,4,5]].values
r_ols = sm.OLS(endog = sonveriler.iloc[:,-1:], exog =X_l)
r = r_ols.fit()
print(r.summary())

AttributeError: module 'statsmodels.formula.api' has no attribute 'OLS'

In [40]:
sonveriler = sonveriler.iloc[:,1:]

import statsmodels.formula.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1 )
X_l = sonveriler.iloc[:,[0,1,2,3,4]].values
r_ols = sm.OLS(endog = sonveriler.iloc[:,-1:], exog =X_l)
r = r_ols.fit()
print(r.summary())

x_train = x_train.iloc[:,1:]
x_test = x_test.iloc[:,1:]

regressor.fit(x_train,y_train)


y_pred = regressor.predict(x_test)

AttributeError: module 'statsmodels.formula.api' has no attribute 'OLS'