In [1]:
import numpy as np

In [2]:
a=np.array([5,6,7,8,9])

In [3]:
type(a)

numpy.ndarray

In [5]:
a

array([5, 6, 7, 8, 9])

In [6]:
c=np.array([10,11,12,13,14])

In [7]:
for i in c:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [9]:
d=np.array([15.5,16.5,17.5,18.5,19.5])

In [10]:
for i in d:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [11]:
e=np.array([1,2,3,4,5,6.5])

In [13]:
for i in e:
    print(type(i)) #Bu sayıların float görünmesinin sebebi pythonun daha hızlı çalışması için floatı 
                   #Başa tutturup hepsini bu şekilde alması

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [14]:
f=np.array([5.5,6.5,7.5,8.5],dtype="int32")

In [15]:
a

array([5, 6, 7, 8, 9])

In [17]:
np.zeros(10,dtype="int32")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones(6)*4

array([4., 4., 4., 4., 4., 4.])

In [22]:
np.full(8,4)

array([4, 4, 4, 4, 4, 4, 4, 4])

In [23]:
np.full(3,15)*2

array([30, 30, 30])

In [25]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.ones([5,2])  #Her zaman kendimiz veri bulamayacağımız için bazen gerekli olabiliryor analiz aşamasında.

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [36]:
np.random.rand(5,3)

array([[0.63405724, 0.01770727, 0.39816755],
       [0.37345978, 0.08944584, 0.11843186],
       [0.78753966, 0.86081095, 0.86700466],
       [0.25508451, 0.67215487, 0.53508984],
       [0.27459079, 0.20933329, 0.23456064]])

In [41]:
np.random.normal(0,20,(5,6)) #np.random.normal(ortalama, standart_sapma, (boyut))

array([[-10.91771246,  14.02601423,  -8.96598247, -13.31751938,
         -5.92051127,   6.70024095],
       [ 22.69749173,  -0.24052183, -22.38511407,  51.2475639 ,
          8.37643257,  -8.09572036],
       [-15.75150005, -13.73423976, -23.8971112 ,  -5.31206417,
          1.44143356,  13.83854874],
       [-43.87277776, -18.21517047,   7.01245045,  -9.75421963,
         13.92237004,  17.16664851],
       [-29.37162549,  22.12939297, -19.4965778 ,  16.87263718,
         19.73943141, -23.62432178]])

In [44]:
np.random.randint(0,100,(3,3)) #np.random.randint(düşük, yüksek, (boyut))

array([[82, 90, 95],
       [91, 15, 75],
       [22, 26, 81]])

In [56]:
a=np.random.randint(5,20,(4,4))

In [57]:
a

array([[18, 19,  7, 13],
       [10, 15, 12, 15],
       [18, 14, 10, 18],
       [18, 14, 10, 11]])

In [48]:
a.ndim #kaç boyutlu bir dizi olduğunu öğrenmek için kullanıyoruz.

2

In [49]:
a.shape

(4, 4)

In [52]:
e.shape

(6,)

In [53]:
e

array([1. , 2. , 3. , 4. , 5. , 6.5])